In [68]:
import pandas as pd
import numpy as np
import datetime as dt
from sklearn.decomposition import PCA

In [51]:
data =  pd.read_csv("swissyield.csv")

In [52]:
date = pd.to_datetime(data['Date'], format="%Y/%m/%d")
data.set_index(date, inplace = True)
data.drop(['Date'], axis = 1, inplace = True)
data1 = data.diff()

In [38]:
data1.head()

2Y     3Y     4Y     5Y     7Y    10Y    20Y    30Y
Date                                                              
2000-08-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2000-09-30 -0.189 -0.102 -0.031  0.018  0.076  0.114  0.107  0.048
2000-10-31 -0.037 -0.034 -0.031 -0.030 -0.028 -0.027 -0.019 -0.003
2000-11-30  0.036 -0.009 -0.055 -0.089 -0.130 -0.156 -0.150 -0.121
2000-12-31 -0.382 -0.356 -0.332 -0.312 -0.275 -0.219 -0.132 -0.137

In [53]:
inputdf = data1[data1.index > dt.datetime(2000,8,31)]
inputdf.head()

2Y     3Y     4Y     5Y     7Y    10Y    20Y    30Y
Date                                                              
2000-09-30 -0.189 -0.102 -0.031  0.018  0.076  0.114  0.107  0.048
2000-10-31 -0.037 -0.034 -0.031 -0.030 -0.028 -0.027 -0.019 -0.003
2000-11-30  0.036 -0.009 -0.055 -0.089 -0.130 -0.156 -0.150 -0.121
2000-12-31 -0.382 -0.356 -0.332 -0.312 -0.275 -0.219 -0.132 -0.137
2001-01-31 -0.070 -0.075 -0.078 -0.078 -0.074 -0.055  0.037  0.092

In [138]:
pca = PCA(n_components=5)
pca.fit(inputdf)
print(pca.explained_variance_ratio_)

pca2 = PCA(n_components = 3)
pca2.fit(inputdf)
print(pca2.explained_variance_ratio_)
print(pca.singular_values_)
print(pca.components_)

[0.79635841 0.14856501 0.04124971 0.00991493 0.00344801]
[0.79635841 0.14856501 0.04124971]
[4.6160777  1.99377933 1.05058036 0.51506681 0.30374085]
[[-0.38268873 -0.4156309  -0.41243348 -0.39760151 -0.36566676 -0.32966306
  -0.2583806  -0.20847424]
 [ 0.39737812  0.34739055  0.20592899  0.06390356 -0.14971138 -0.33060588
  -0.51654571 -0.52572503]
 [-0.52592741 -0.14944759  0.12846106  0.29304889  0.40731708  0.33311495
  -0.21431464 -0.52524503]
 [ 0.50061977 -0.17337415 -0.35542974 -0.28498017  0.05587192  0.45272251
   0.272903   -0.47877119]
 [-0.32758758  0.36050728  0.22404994 -0.07487446 -0.36788449 -0.11690848
   0.64144492 -0.38269849]]


In [22]:
#df = inputdf.transpose()

In [101]:
muhat = np.array(inputdf.mean(axis =0))
muhat

array([-0.02854622, -0.02688235, -0.02521008, -0.02370588, -0.02143697,
       -0.01966387, -0.0189916 , -0.01969748])

In [60]:
covhat = inputdf.cov()
covhat

2Y        3Y        4Y        5Y        7Y       10Y       20Y  \
2Y   0.035005  0.033808  0.030170  0.026598  0.021422  0.017244  0.012145   
3Y   0.033808  0.035668  0.033383  0.030246  0.024989  0.020227  0.013703   
4Y   0.030170  0.033383  0.032624  0.030625  0.026575  0.022274  0.015298   
5Y   0.026598  0.030246  0.030625  0.029694  0.027041  0.023564  0.016655   
7Y   0.021422  0.024989  0.026575  0.027041  0.026570  0.024784  0.018706   
10Y  0.017244  0.020227  0.022274  0.023564  0.024784  0.024846  0.020666   
20Y  0.012145  0.013703  0.015298  0.016655  0.018706  0.020666  0.021975   
30Y  0.009508  0.010316  0.011563  0.012719  0.014463  0.016186  0.019437   

          30Y  
2Y   0.009508  
3Y   0.010316  
4Y   0.011563  
5Y   0.012719  
7Y   0.014463  
10Y  0.016186  
20Y  0.019437  
30Y  0.020372

In [83]:
from numpy.linalg import eig
values, vectors = eig(covhat)
values

array([1.80577740e-01, 3.36877627e-02, 9.35355159e-03, 2.24825269e-03,
       7.81851738e-04, 1.00951279e-04, 4.03517437e-06, 2.12941940e-07])

In [67]:
vectors

array([[ 0.38268873, -0.39737812,  0.52592741,  0.50061977, -0.32758758,
        -0.22237809, -0.10167402, -0.03628947],
       [ 0.4156309 , -0.34739055,  0.14944759, -0.17337415,  0.36050728,
         0.53472959,  0.42425816,  0.24141533],
       [ 0.41243348, -0.20592899, -0.12846106, -0.35542974,  0.22404994,
        -0.0553591 , -0.43077008, -0.6370506 ],
       [ 0.39760151, -0.06390356, -0.29304889, -0.28498017, -0.07487446,
        -0.43266527, -0.21920766,  0.65565281],
       [ 0.36566676,  0.14971138, -0.40731708,  0.05587192, -0.36788449,
        -0.17711187,  0.64235998, -0.30904934],
       [ 0.32966306,  0.33060588, -0.33311495,  0.45272251, -0.11690848,
         0.54170672, -0.38728737,  0.09483404],
       [ 0.2583806 ,  0.51654571,  0.21431464,  0.272903  ,  0.64144492,
        -0.34992722,  0.1092788 , -0.01306417],
       [ 0.20847424,  0.52572503,  0.52524503, -0.47877119, -0.38269849,
         0.16457379, -0.03863725,  0.00346167]])

In [139]:
print(values[0])
print(values[1])

print(vectors[0])
print(vectors[1])

vectors = pd.DataFrame(vectors)
vectors

0.18057773981517844
0.03368776269656325
[[ 0.38268873 -0.39737812  0.52592741  0.50061977 -0.32758758 -0.22237809
  -0.10167402 -0.03628947]]
[[ 0.4156309  -0.34739055  0.14944759 -0.17337415  0.36050728  0.53472959
   0.42425816  0.24141533]]


0         1         2         3         4         5         6  \
0  0.382689 -0.397378  0.525927  0.500620 -0.327588 -0.222378 -0.101674   
1  0.415631 -0.347391  0.149448 -0.173374  0.360507  0.534730  0.424258   
2  0.412433 -0.205929 -0.128461 -0.355430  0.224050 -0.055359 -0.430770   
3  0.397602 -0.063904 -0.293049 -0.284980 -0.074874 -0.432665 -0.219208   
4  0.365667  0.149711 -0.407317  0.055872 -0.367884 -0.177112  0.642360   
5  0.329663  0.330606 -0.333115  0.452723 -0.116908  0.541707 -0.387287   
6  0.258381  0.516546  0.214315  0.272903  0.641445 -0.349927  0.109279   
7  0.208474  0.525725  0.525245 -0.478771 -0.382698  0.164574 -0.038637   

          7  
0 -0.036289  
1  0.241415  
2 -0.637051  
3  0.655653  
4 -0.309049  
5  0.094834  
6 -0.013064  
7  0.003462

In [131]:
PCs = np.asmatrix(inputdf - muhat) * np.asmatrix(vectors)
PCdf = pd.DataFrame(PCs)
PCdf.set_index(inputdf.index, inplace = True)
PCdf.rename(columns = dict(zip(PCdf.columns, inputdf.columns)), inplace = True)
PCdf.cov()

2Y            3Y            4Y            5Y            7Y  \
2Y   1.805777e-01  3.621983e-17  1.173975e-17  2.262532e-18 -9.353210e-18   
3Y   3.621983e-17  3.368776e-02 -4.277159e-19  2.139763e-19 -1.288842e-17   
4Y   1.173975e-17 -4.277159e-19  9.353552e-03  8.442856e-18 -1.712498e-18   
5Y   2.262532e-18  2.139763e-19  8.442856e-18  2.248253e-03  7.578538e-19   
7Y  -9.353210e-18 -1.288842e-17 -1.712498e-18  7.578538e-19  7.818517e-04   
10Y  2.126439e-17  5.883105e-18  4.731200e-18  1.318860e-18 -3.237011e-18   
20Y -1.233076e-17  6.689940e-18 -1.785049e-17 -1.228607e-17  4.095075e-18   
30Y -1.003587e-17  4.989473e-18  7.946840e-19  5.602629e-18  1.219239e-17   

              10Y           20Y           30Y  
2Y   2.126439e-17 -1.233076e-17 -1.003587e-17  
3Y   5.883105e-18  6.689940e-18  4.989473e-18  
4Y   4.731200e-18 -1.785049e-17  7.946840e-19  
5Y   1.318860e-18 -1.228607e-17  5.602629e-18  
7Y  -3.237011e-18  4.095075e-18  1.219239e-17  
10Y  1.009513e-04  1.337356e-19  2.130501e-17  
20Y  1.337356e-19  4.035174e-06  1.189730e-18  
30Y  2.130501e-17  1.189730e-18  2.129419e-07

In [134]:
print(pd.DataFrame(vectors))

          0         1         2         3         4         5         6  \
0  0.382689 -0.397378  0.525927  0.500620 -0.327588 -0.222378 -0.101674   
1  0.415631 -0.347391  0.149448 -0.173374  0.360507  0.534730  0.424258   
2  0.412433 -0.205929 -0.128461 -0.355430  0.224050 -0.055359 -0.430770   
3  0.397602 -0.063904 -0.293049 -0.284980 -0.074874 -0.432665 -0.219208   
4  0.365667  0.149711 -0.407317  0.055872 -0.367884 -0.177112  0.642360   
5  0.329663  0.330606 -0.333115  0.452723 -0.116908  0.541707 -0.387287   
6  0.258381  0.516546  0.214315  0.272903  0.641445 -0.349927  0.109279   
7  0.208474  0.525725  0.525245 -0.478771 -0.382698  0.164574 -0.038637   

          7  
0 -0.036289  
1  0.241415  
2 -0.637051  
3  0.655653  
4 -0.309049  
5  0.094834  
6 -0.013064  
7  0.003462  


In [136]:
PCdf

2Y        3Y        4Y        5Y        7Y       10Y  \
Date                                                                     
2000-09-30  0.047930  0.247831 -0.128745 -0.009202  0.024499 -0.000008   
2000-10-31 -0.012423  0.012792  0.010964 -0.010831 -0.003746  0.001057   
2000-11-30 -0.145726 -0.203810  0.067930  0.003369 -0.005872 -0.000347   
2000-12-31 -0.725298  0.112481 -0.027332 -0.007775  0.038976  0.001497   
2001-01-31 -0.072339  0.115622  0.097549 -0.035306  0.005108 -0.001141   
2001-02-28  0.021482  0.005400  0.011207  0.018043 -0.005095  0.000943   
2001-03-31 -0.272015  0.034663  0.066673 -0.100368 -0.005420  0.000415   
2001-04-30  0.599691  0.134054  0.046102 -0.007770  0.003866 -0.001369   
2001-05-31  0.114521  0.014623 -0.002765 -0.005531 -0.023796  0.004938   
2001-06-30 -0.294907 -0.148063  0.017101  0.000356 -0.002000 -0.003376   
2001-07-31 -0.076546  0.011987 -0.011804  0.029454  0.013272 -0.001700   
2001-08-31 -0.219499  0.052540 -0.147690 -0.032467  0.009281  0.002631   
2001-09-30 -0.433613  0.269685 -0.151641  0.009529  0.025045  0.013230   
2001-10-31 -0.771885 -0.072194 -0.078500 -0.055907  0.008786  0.002518   
2001-11-30  0.797234  0.055974  0.075224  0.042227 -0.007874 -0.001592   
2001-12-31  0.674768  0.122779 -0.180918 -0.025884 -0.018041  0.001895   
2002-01-31  0.365682 -0.052188  0.040106 -0.064401  0.006225 -0.009710   
2002-02-28 -0.130377  0.094863 -0.035145  0.066467 -0.015796  0.013365   
2002-03-31  0.315321 -0.046545  0.059033 -0.026579  0.045601 -0.011405   
2002-04-30 -0.374908  0.155391  0.044811 -0.018383 -0.030526  0.007079   
2002-05-31 -0.242228  0.094137 -0.030386 -0.000268  0.043244  0.000413   
2002-06-30 -0.336697  0.027374  0.111495 -0.015701  0.007163  0.000850   
2002-07-31 -0.691710  0.153515 -0.341574  0.057857  0.010661  0.015047   
2002-08-31 -0.216317  0.172214  0.035953 -0.023571  0.008777  0.002505   
2002-09-30 -0.770290 -0.227851  0.239743 -0.020017 -0.025328  0.004366   
2002-10-31  0.010650  0.236754 -0.142251  0.002689  0.036356 -0.005692   
2002-11-30  0.120900 -0.071590  0.189518  0.013310  0.005583 -0.005673   
2002-12-31 -0.998799  0.057314  0.084797 -0.106650 -0.014906  0.002782   
2003-01-31  0.047672 -0.093428 -0.028423  0.065471  0.013448 -0.003938   
2003-02-28 -0.157665  0.156679  0.003151 -0.012014 -0.009317  0.007260   
...              ...       ...       ...       ...       ...       ...   
2008-02-29  0.327312  0.031953 -0.118903 -0.021001 -0.023034 -0.023473   
2008-03-31 -0.106427  0.089289 -0.024783 -0.019714  0.006912  0.000836   
2008-04-30  0.647551  0.083331 -0.068329 -0.076191  0.017643 -0.000831   
2008-05-31  0.410495 -0.202337  0.000342 -0.020628  0.016072  0.010252   
2008-06-30  0.328690 -0.232218  0.030740  0.005060  0.006736  0.007519   
2008-07-31 -0.411679  0.068269  0.002499  0.027700 -0.016339 -0.010799   
2008-08-31 -0.476273 -0.124117  0.280907  0.182710 -0.058406  0.000477   
2008-09-30 -1.427340  0.574348 -0.059903  0.033605 -0.033261 -0.024360   
2008-10-31  0.292080  0.170001 -0.014256 -0.120471  0.073490  0.039016   
2008-11-30 -0.834662 -0.765820 -0.186569 -0.113510  0.100912  0.022485   
2008-12-31 -0.718451  0.340861 -0.270165 -0.038109 -0.010937 -0.012930   
2009-01-31 -0.160923  0.489904  0.069751  0.006882 -0.011850  0.005122   
2009-02-28  0.054745 -0.156169  0.002198  0.020373 -0.010785 -0.007135   
2009-03-31  0.089032  0.008495  0.025754 -0.013163  0.012066  0.009165   
2009-04-30  0.022424  0.090954 -0.029821 -0.009451 -0.006170 -0.006353   
2009-05-31  0.650549  0.547509  0.071873 -0.040814  0.000430  0.013102   
2009-06-30  0.005763 -0.092844  0.054125  0.012456  0.005763  0.006292   
2009-07-31 -0.511412 -0.288499  0.068430  0.041502  0.007275  0.004016   
2009-08-31 -0.059811 -0.028194  0.088808  0.017276  0.003195  0.005005   
2009-09-30  0.293400 -0.064113  0.024096 -0.033723  0.014075 -0.001666   
2009-10-31  0.174932 -0.073992 -0.065481  0.053986  0.040534 -0.007366   
2009-11-30 -0.434441 -

In [137]:
PCdf.to_csv("PCA.csv")